{% set name = "dataflows-tabulator" %}
{% set version = "1.54.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dataflows-tabulator-{{ version }}.tar.gz
  sha256: fc87953d208f184043604e5dce2ab6766617241918859980129b2703d16c0683

build:
  entry_points:
    - tabulator = tabulator.__main__:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - six >=1.9
    - click >=6.0
    - requests >=2.8
    - chardet >=3.0
    - boto3 >=1.9
    - unicodecsv >=0.14
    - ijson >=3.0.3
    - jsonlines >=1.1
    - sqlalchemy >=0.9.6
    - linear-tsv >=1.0
    - xlrd >=1.0
    - openpyxl >=2.6

test:
  imports:
    - tabulator
  commands:
    - pip check
    - tabulator --help
  requires:
    - pip

about:
  home: https://github.com/akariv/tabulator-py
  summary: Consistent interface for stream reading and writing tabular data (csv/xls/json/etc)
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
